version: '3'

services:
  biascorrector_container:
    image: harbor.miracum.org/biascorrector/biascorrector_img:0.1.4
    restart: unless-stopped
    ports:
    - "4038:3838"

# login into container:
# docker exec -it biascorrector_container bash

# monitor log-file in container:
# tail -f /srv/shiny-server/app/biascorrector.log
