version: '3.7'

services:
  biascorrector_container:
    image: docker.miracum.org/biascorrector/biascorrector_img:0.0.5
    restart: unless-stopped
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.frontend.rule=Host:${HOST_NAME};PathPrefixStrip:/biascorrector/
        - traefik.port=3838
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true

# deploy to stack:
# sudo HOST_NAME=your.hostname.org docker stack deploy --compose-file docker-compose.swarm.yml biascorrector
