version: '3'

services:
  biascorrector_container:
    image: biascorrector
    restart: unless-stopped
    ports:
    - "3838:3838"

# login into container:
# docker exec -it biascorrector_container bash

# monitor log-file in container:
# tail -f /srv/shiny-server/app/biascorrector.log
